[package]
name = "zeen-ast"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
lasso = "0.7.3"
miette = { version = "7.6.0", features = ["fancy"] }
smallvec = "1.15.1"
zeen-lexer = {path = "../zeen-lexer"}
