[package]
name = "zeen"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bumpalo = { version = "3.20.2", features = ["boxed"] }
lasso = "0.7.3"
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2.0.18"
zeen-driver = {path = "../zeen-driver"}
zeen-lexer = {path = "../zeen-lexer"}
zeen-parser = {path = "../zeen-parser"}
