[package]
name = "zeen"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bumpalo = { version = "3.20.2", features = ["boxed"] }
lasso = "0.7.3"
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2.0.18"
clap = { version = "4.6.2", features = ["derive"] }
colored = "3.1.1"
inkwell = { version = "0.10.0", features = ["llvm22-1"] }

zeen-driver = {path = "../zeen-driver"}
zeen-lexer = {path = "../zeen-lexer"}
zeen-ast = {path = "../zeen-ast"}
zeen-parser = {path = "../zeen-parser"}
zeen-resolve = {path = "../zeen-resolve"}
zeen-hir = { path = "../zeen-hir" }
zeen-typecheck = { path = "../zeen-typecheck" }
zeen-mir = { path = "../zeen-mir" }
zeen-flow = { path = "../zeen-flow" }
zeen-codegen-llvm = { path = "../zeen-codegen-llvm" }
zeen-linker = { path = "../zeen-linker" }

[dev-dependencies]
anyhow = "1.0.104"
assert_cmd = "2.2.2"
