[package]
name = "zeen-driver"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.6.2", features = ["derive"] }
miette = { version = "7.6.0", features = ["fancy"] }
