[package]
name = "zeen-resolve"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bumpalo = "3.20.2"
lasso = "0.7.3"
miette = "7.6.0"
thiserror = "2.0.18"
smol_str = "0.3.6"
smallvec = "1.15.1"
zeen-ast = {path = "../zeen-ast"}
zeen-driver = {path = "../zeen-driver"}
zeen-lexer = {path = "../zeen-lexer"}
zeen-parser = {path = "../zeen-parser"}
