[package]
name = "zeen-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
tower-lsp-server = "0.23.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "io-std", "sync"] }
miette = { version = "7.6.0" }

zeen-lexer = { path = "../compiler/zeen-lexer" }
zeen-parser = { path = "../compiler/zeen-parser" }
zeen-driver = { path = "../compiler/zeen-driver" }
