# Justfile is an analogue for Makefile.
# Utility: https://github.com/casey/just

# Zeen Compiler Justfile
# https://github.com/mealet/zeen

# Usage: just <recipe>
# (used in development purposes)

default:
    @just --list

# Run the compiler on `test.zn` file
run:
  touch test.zn
  cargo run -- test.zn output

mir:
  touch test.zn
  cargo run -- test.zn output --emit MIR
  printf "\n" && cat test.zn.mir

# Run the compiler on `test.zn` (release mode)
run-release:
  touch test.zn
  cargo run --release -- test.zn output

nvim:
  touch test.zn
  nvim test.zn

  {{just_executable()}} run

# Run tests (nextest if available, otherwise cargo test)
test:
  #!/usr/bin/env sh
  if cargo nextest --version > /dev/null 2>&1; then
      cargo nextest run
  else
      echo "nextest not found, falling back to cargo test"
      cargo test
  fi

# Build a release binary
build:
    cargo build --release

# Apply cargo formatter
fmt:
  cargo fmt -- --emit=files

# Apply cargo clippy
clippy:
  cargo clippy --fix --allow-dirty -- -D warnings
