[package]
name = "zeen-mir"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
lasso = "0.7.3"

zeen-ast = {path = "../zeen-ast"}
zeen-resolve = {path = "../zeen-resolve"}
zeen-typecheck = {path = "../zeen-typecheck"}
zeen-types = {path = "../zeen-types"}
zeen-hir = {path = "../zeen-hir"}

[dev-dependencies]
bumpalo = "3.20.2"
zeen-lexer = {path = "../zeen-lexer"}
zeen-parser = {path = "../zeen-parser"}
zeen-driver = {path = "../zeen-driver"}
