[package]
name = "zeen-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
lasso = "0.7.3"

zeen-ast = {path = "../zeen-ast"}
zeen-hir = {path = "../zeen-hir"}
zeen-resolve = {path = "../zeen-resolve"}

[dev-dependencies]
miette = { version = "7.6.0", features = ["fancy"] }
