[package]
name = "zeen-flow"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
lasso = "0.7.3"
miette = "7.6.0"
thiserror = "2.0.18"
smol_str = "0.3.6"

zeen-ast = {path = "../zeen-ast"}
zeen-mir = {path = "../zeen-mir"}
zeen-resolve = {path = "../zeen-resolve"}
zeen-typecheck = {path = "../zeen-typecheck"}
zeen-types = {path = "../zeen-types"}

[dev-dependencies]
bumpalo = "3.20.2"
zeen-driver = {path = "../zeen-driver"}
zeen-hir = {path = "../zeen-hir"}
zeen-lexer = {path = "../zeen-lexer"}
zeen-parser = {path = "../zeen-parser"}