name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@stable

    # - name: 🖱️ LLVM Install
    #   uses: ZhongRuoyu/setup-llvm@405ac952f13f3ee4d376adc2b7a96e5f48d1f73f
    #   with:
    #     llvm-version: 18

    - name: ⚙️ Install Nextest
      uses: taiki-e/install-action@nextest

    - name: ⌛ Packages Tests
      run: |
        cd compiler
        cargo nextest run
