name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ./compiler

    runs-on: ubuntu-latest

    steps:

    # Checkout
    - name: Checkout
      uses: actions/checkout@v5

    # Install Rust
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          override: true

    # Install LLVM
    - name: Install LLVM and Clang
      uses: ZhongRuoyu/setup-llvm@v0.1.1
      with:
          llvm-version: 22

    # Install Nextest
    - name: Install Nextest
      uses: taiki-e/install-action@nextest

    # Setup Zeen Standard Library
    - name: Set ZEEN_STD
      run: echo "ZEEN_STD=$GITHUB_WORKSPACE/lib/std" >> "$GITHUB_ENV"

    # Run tests
    - name: Packages Tests
      run: cargo nextest run
